### ISSUE TITLE
Request about the value of g:rainbow_colors_black of README.md

### ISSUE THREAD

**Issue by makotortat** [adi/vim-indent-rainbow#3]
I start to use this plug-in, and it works for me. Thank you.

I have a reuqest to consider about the value of g:rainbow_colors_black of README.md, or rainbow.vim. I use the following value.
`let g:rainbow_colors_black= [ 238, 239, 240, 241, 242, 243 ]`

This reason is below.
I usually use the Windows Terminal in Tango Dark. When I tried to use this plug-in at the first time, I could find any change after press F9. So I used 256-colors.sh, and I found the difficulty to identify difference of colors from 232 to 236.
![SharedScreenshot_colors](https://user-images.githubusercontent.com/28667425/170858184-47b59bb4-7f2d-4e8a-9bc7-f1c5d1b362c4.jpg)

I would like to share this plug-in with my colleagues.
Please consider about change of the value.

**Comment by adi** [comment]
The code of the plugin allows you to specify what colours work for you:
```
if !exists("g:rainbow_colors_black")
    let g:rainbow_colors_black= [ 234, 235, 236, 237, 238, 239 ]
endif
```
So if you just define this:
```
let g:rainbow_colors_black= [ 238, 239, 240, 241, 242, 243 ]
```
it should overrride your setting.

**Comment by makotortat** [comment]
Thank you for your response.
I understand it.
